# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_sicen.ui'
#
# Created: Fri Nov 28 15:42:25 2014
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_SICEN(object):
    def setupUi(self, SICEN):
        SICEN.setObjectName(_fromUtf8("SICEN"))
        SICEN.resize(560, 526)
        self.buttonBox = QtGui.QDialogButtonBox(SICEN)
        self.buttonBox.setGeometry(QtCore.QRect(390, 490, 161, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.Titre = QtGui.QLabel(SICEN)
        self.Titre.setGeometry(QtCore.QRect(110, 10, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.Titre.setFont(font)
        self.Titre.setObjectName(_fromUtf8("Titre"))
        self.Emprise = QtGui.QTabWidget(SICEN)
        self.Emprise.setGeometry(QtCore.QRect(10, 50, 541, 431))
        self.Emprise.setTabPosition(QtGui.QTabWidget.North)
        self.Emprise.setTabShape(QtGui.QTabWidget.Rounded)
        self.Emprise.setObjectName(_fromUtf8("Emprise"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 9, 511, 81))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayoutWidget_5 = QtGui.QWidget(self.groupBox_4)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(10, 20, 491, 51))
        self.gridLayoutWidget_5.setObjectName(_fromUtf8("gridLayoutWidget_5"))
        self.gridLayout_5 = QtGui.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.observateur_1 = QtGui.QComboBox(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.observateur_1.setFont(font)
        self.observateur_1.setObjectName(_fromUtf8("observateur_1"))
        self.gridLayout_5.addWidget(self.observateur_1, 0, 0, 1, 1)
        self.observateur_3 = QtGui.QComboBox(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.observateur_3.setFont(font)
        self.observateur_3.setObjectName(_fromUtf8("observateur_3"))
        self.gridLayout_5.addWidget(self.observateur_3, 1, 0, 1, 1)
        self.observateur_2 = QtGui.QComboBox(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.observateur_2.setFont(font)
        self.observateur_2.setObjectName(_fromUtf8("observateur_2"))
        self.gridLayout_5.addWidget(self.observateur_2, 0, 1, 1, 1)
        self.observateur_4 = QtGui.QComboBox(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.observateur_4.setFont(font)
        self.observateur_4.setObjectName(_fromUtf8("observateur_4"))
        self.gridLayout_5.addWidget(self.observateur_4, 1, 1, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 100, 511, 71))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayoutWidget_6 = QtGui.QWidget(self.groupBox_5)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(10, 20, 491, 41))
        self.gridLayoutWidget_6.setObjectName(_fromUtf8("gridLayoutWidget_6"))
        self.gridLayout_6 = QtGui.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label = QtGui.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(True)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(True)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_6.addWidget(self.label_2, 0, 1, 1, 1)
        self.nom_com_1 = QtGui.QComboBox(self.gridLayoutWidget_6)
        self.nom_com_1.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.nom_com_1.setFont(font)
        self.nom_com_1.setObjectName(_fromUtf8("nom_com_1"))
        self.gridLayout_6.addWidget(self.nom_com_1, 1, 0, 1, 1)
        self.nom_com_2 = QtGui.QComboBox(self.gridLayoutWidget_6)
        self.nom_com_2.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.nom_com_2.setFont(font)
        self.nom_com_2.setObjectName(_fromUtf8("nom_com_2"))
        self.gridLayout_6.addWidget(self.nom_com_2, 1, 1, 1, 1)
        self.groupBox_7 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 180, 511, 221))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayoutWidget_8 = QtGui.QWidget(self.groupBox_7)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(10, 20, 491, 191))
        self.gridLayoutWidget_8.setObjectName(_fromUtf8("gridLayoutWidget_8"))
        self.gridLayout_8 = QtGui.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(True)
        font.setBold(False)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_8.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(True)
        font.setBold(False)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_8.addWidget(self.label_4, 0, 1, 1, 1)
        self.date_min = QtGui.QCalendarWidget(self.gridLayoutWidget_8)
        self.date_min.setObjectName(_fromUtf8("date_min"))
        self.gridLayout_8.addWidget(self.date_min, 1, 0, 1, 1)
        self.date_max = QtGui.QCalendarWidget(self.gridLayoutWidget_8)
        self.date_max.setObjectName(_fromUtf8("date_max"))
        self.gridLayout_8.addWidget(self.date_max, 1, 1, 1, 1)
        self.Emprise.addTab(self.tab_2, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox_8 = QtGui.QGroupBox(self.tab)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 10, 511, 51))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.gridLayoutWidget_9 = QtGui.QWidget(self.groupBox_8)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(10, 20, 491, 21))
        self.gridLayoutWidget_9.setObjectName(_fromUtf8("gridLayoutWidget_9"))
        self.gridLayout_9 = QtGui.QGridLayout(self.gridLayoutWidget_9)
        self.gridLayout_9.setMargin(0)
        self.gridLayout_9.setHorizontalSpacing(100)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.Animalia = QtGui.QCheckBox(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.Animalia.setFont(font)
        self.Animalia.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Animalia.setObjectName(_fromUtf8("Animalia"))
        self.gridLayout_9.addWidget(self.Animalia, 0, 0, 1, 1)
        self.Plantae = QtGui.QCheckBox(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.Plantae.setFont(font)
        self.Plantae.setObjectName(_fromUtf8("Plantae"))
        self.gridLayout_9.addWidget(self.Plantae, 0, 1, 1, 1)
        self.gridLayoutWidget_10 = QtGui.QWidget(self.tab)
        self.gridLayoutWidget_10.setGeometry(QtCore.QRect(9, 90, 511, 152))
        self.gridLayoutWidget_10.setObjectName(_fromUtf8("gridLayoutWidget_10"))
        self.gridLayout_11 = QtGui.QGridLayout(self.gridLayoutWidget_10)
        self.gridLayout_11.setMargin(0)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget_10)
        self.label_6.setMinimumSize(QtCore.QSize(500, 20))
        self.label_6.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(True)
        font.setBold(False)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_11.addWidget(self.label_6, 4, 0, 1, 1)
        self.nom_vern = QtGui.QComboBox(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.nom_vern.setFont(font)
        self.nom_vern.setObjectName(_fromUtf8("nom_vern"))
        self.gridLayout_11.addWidget(self.nom_vern, 3, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget_10)
        self.label_5.setMinimumSize(QtCore.QSize(500, 20))
        self.label_5.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(True)
        font.setBold(False)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_11.addWidget(self.label_5, 2, 0, 1, 1)
        self.nom_complet = QtGui.QComboBox(self.gridLayoutWidget_10)
        self.nom_complet.setMinimumSize(QtCore.QSize(500, 0))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.nom_complet.setFont(font)
        self.nom_complet.setObjectName(_fromUtf8("nom_complet"))
        self.gridLayout_11.addWidget(self.nom_complet, 5, 0, 1, 1)
        self.ordre = QtGui.QComboBox(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.ordre.setFont(font)
        self.ordre.setObjectName(_fromUtf8("ordre"))
        self.gridLayout_11.addWidget(self.ordre, 1, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.gridLayoutWidget_10)
        self.label_13.setMinimumSize(QtCore.QSize(500, 20))
        self.label_13.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(True)
        font.setBold(False)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_11.addWidget(self.label_13, 0, 0, 1, 1)
        self.Emprise.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.protections = QtGui.QToolBox(self.tab_3)
        self.protections.setGeometry(QtCore.QRect(10, 10, 511, 391))
        self.protections.setFrameShape(QtGui.QFrame.NoFrame)
        self.protections.setFrameShadow(QtGui.QFrame.Plain)
        self.protections.setLineWidth(1)
        self.protections.setObjectName(_fromUtf8("protections"))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 511, 310))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.groupBox = QtGui.QGroupBox(self.page_2)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 511, 121))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.groupBox)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 491, 88))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setHorizontalSpacing(50)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.LRD_38 = QtGui.QCheckBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.LRD_38.setFont(font)
        self.LRD_38.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.LRD_38.setObjectName(_fromUtf8("LRD_38"))
        self.gridLayout_2.addWidget(self.LRD_38, 3, 0, 1, 1)
        self.LRD_01 = QtGui.QCheckBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.LRD_01.setFont(font)
        self.LRD_01.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.LRD_01.setObjectName(_fromUtf8("LRD_01"))
        self.gridLayout_2.addWidget(self.LRD_01, 0, 0, 1, 1)
        self.LRD_07 = QtGui.QCheckBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.LRD_07.setFont(font)
        self.LRD_07.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.LRD_07.setObjectName(_fromUtf8("LRD_07"))
        self.gridLayout_2.addWidget(self.LRD_07, 1, 0, 1, 1)
        self.LRD_26 = QtGui.QCheckBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.LRD_26.setFont(font)
        self.LRD_26.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.LRD_26.setObjectName(_fromUtf8("LRD_26"))
        self.gridLayout_2.addWidget(self.LRD_26, 2, 0, 1, 1)
        self.LRD_42 = QtGui.QCheckBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.LRD_42.setFont(font)
        self.LRD_42.setObjectName(_fromUtf8("LRD_42"))
        self.gridLayout_2.addWidget(self.LRD_42, 0, 1, 1, 1)
        self.LRD_69 = QtGui.QCheckBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.LRD_69.setFont(font)
        self.LRD_69.setObjectName(_fromUtf8("LRD_69"))
        self.gridLayout_2.addWidget(self.LRD_69, 1, 1, 1, 1)
        self.LRD_73 = QtGui.QCheckBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.LRD_73.setFont(font)
        self.LRD_73.setObjectName(_fromUtf8("LRD_73"))
        self.gridLayout_2.addWidget(self.LRD_73, 2, 1, 1, 1)
        self.LRD_74 = QtGui.QCheckBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.LRD_74.setFont(font)
        self.LRD_74.setObjectName(_fromUtf8("LRD_74"))
        self.gridLayout_2.addWidget(self.LRD_74, 3, 1, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.page_2)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 130, 511, 71))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.groupBox_2)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 491, 42))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setHorizontalSpacing(50)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.LRR_Flore = QtGui.QCheckBox(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.LRR_Flore.setFont(font)
        self.LRR_Flore.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.LRR_Flore.setObjectName(_fromUtf8("LRR_Flore"))
        self.gridLayout_3.addWidget(self.LRR_Flore, 0, 0, 1, 1)
        self.LRR_Oiseaux = QtGui.QCheckBox(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.LRR_Oiseaux.setFont(font)
        self.LRR_Oiseaux.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.LRR_Oiseaux.setObjectName(_fromUtf8("LRR_Oiseaux"))
        self.gridLayout_3.addWidget(self.LRR_Oiseaux, 1, 0, 1, 1)
        self.LRR_Autre = QtGui.QCheckBox(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.LRR_Autre.setFont(font)
        self.LRR_Autre.setObjectName(_fromUtf8("LRR_Autre"))
        self.gridLayout_3.addWidget(self.LRR_Autre, 0, 1, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.page_2)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 210, 511, 71))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayoutWidget_4 = QtGui.QWidget(self.groupBox_3)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 20, 491, 42))
        self.gridLayoutWidget_4.setObjectName(_fromUtf8("gridLayoutWidget_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_4.setHorizontalSpacing(50)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.LRN_Autre = QtGui.QCheckBox(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.LRN_Autre.setFont(font)
        self.LRN_Autre.setObjectName(_fromUtf8("LRN_Autre"))
        self.gridLayout_4.addWidget(self.LRN_Autre, 1, 1, 1, 1)
        self.LRN_Flore = QtGui.QCheckBox(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.LRN_Flore.setFont(font)
        self.LRN_Flore.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.LRN_Flore.setObjectName(_fromUtf8("LRN_Flore"))
        self.gridLayout_4.addWidget(self.LRN_Flore, 0, 0, 1, 1)
        self.LRN_Oiseaux = QtGui.QCheckBox(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.LRN_Oiseaux.setFont(font)
        self.LRN_Oiseaux.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.LRN_Oiseaux.setObjectName(_fromUtf8("LRN_Oiseaux"))
        self.gridLayout_4.addWidget(self.LRN_Oiseaux, 1, 0, 1, 1)
        self.LRN_Ortho = QtGui.QCheckBox(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.LRN_Ortho.setFont(font)
        self.LRN_Ortho.setObjectName(_fromUtf8("LRN_Ortho"))
        self.gridLayout_4.addWidget(self.LRN_Ortho, 0, 1, 1, 1)
        self.gridLayoutWidget_11 = QtGui.QWidget(self.page_2)
        self.gridLayoutWidget_11.setGeometry(QtCore.QRect(6, 290, 501, 19))
        self.gridLayoutWidget_11.setObjectName(_fromUtf8("gridLayoutWidget_11"))
        self.gridLayout_12 = QtGui.QGridLayout(self.gridLayoutWidget_11)
        self.gridLayout_12.setMargin(0)
        self.gridLayout_12.setHorizontalSpacing(50)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.UICN = QtGui.QCheckBox(self.gridLayoutWidget_11)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.UICN.setFont(font)
        self.UICN.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.UICN.setObjectName(_fromUtf8("UICN"))
        self.gridLayout_12.addWidget(self.UICN, 0, 0, 1, 1)
        self.LRE = QtGui.QCheckBox(self.gridLayoutWidget_11)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.LRE.setFont(font)
        self.LRE.setObjectName(_fromUtf8("LRE"))
        self.gridLayout_12.addWidget(self.LRE, 0, 1, 1, 1)
        self.protections.addItem(self.page_2, _fromUtf8(""))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.page.setObjectName(_fromUtf8("page"))
        self.PATRIMONIALITE = QtGui.QCheckBox(self.page)
        self.PATRIMONIALITE.setGeometry(QtCore.QRect(140, 10, 251, 17))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.PATRIMONIALITE.setFont(font)
        self.PATRIMONIALITE.setObjectName(_fromUtf8("PATRIMONIALITE"))
        self.gridLayoutWidget = QtGui.QWidget(self.page)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 40, 501, 88))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setHorizontalSpacing(50)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.PATRI38 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.PATRI38.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.PATRI38.setObjectName(_fromUtf8("PATRI38"))
        self.gridLayout.addWidget(self.PATRI38, 3, 0, 1, 1)
        self.PATRI01 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.PATRI01.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.PATRI01.setObjectName(_fromUtf8("PATRI01"))
        self.gridLayout.addWidget(self.PATRI01, 0, 0, 1, 1)
        self.PATRI07 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.PATRI07.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.PATRI07.setObjectName(_fromUtf8("PATRI07"))
        self.gridLayout.addWidget(self.PATRI07, 1, 0, 1, 1)
        self.PATRI26 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.PATRI26.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.PATRI26.setObjectName(_fromUtf8("PATRI26"))
        self.gridLayout.addWidget(self.PATRI26, 2, 0, 1, 1)
        self.PATRI42 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.PATRI42.setObjectName(_fromUtf8("PATRI42"))
        self.gridLayout.addWidget(self.PATRI42, 0, 1, 1, 1)
        self.PATRI69 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.PATRI69.setObjectName(_fromUtf8("PATRI69"))
        self.gridLayout.addWidget(self.PATRI69, 1, 1, 1, 1)
        self.PATRI73 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.PATRI73.setObjectName(_fromUtf8("PATRI73"))
        self.gridLayout.addWidget(self.PATRI73, 2, 1, 1, 1)
        self.PATRI74 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.PATRI74.setObjectName(_fromUtf8("PATRI74"))
        self.gridLayout.addWidget(self.PATRI74, 3, 1, 1, 1)
        self.ZNIEFF = QtGui.QCheckBox(self.page)
        self.ZNIEFF.setGeometry(QtCore.QRect(140, 140, 221, 17))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.ZNIEFF.setFont(font)
        self.ZNIEFF.setObjectName(_fromUtf8("ZNIEFF"))
        self.protections.addItem(self.page, _fromUtf8(""))
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.groupBox_6 = QtGui.QGroupBox(self.page_3)
        self.groupBox_6.setGeometry(QtCore.QRect(0, 10, 511, 51))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayoutWidget_7 = QtGui.QWidget(self.groupBox_6)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(10, 20, 491, 21))
        self.gridLayoutWidget_7.setObjectName(_fromUtf8("gridLayoutWidget_7"))
        self.gridLayout_7 = QtGui.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setHorizontalSpacing(50)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.PD_42 = QtGui.QCheckBox(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.PD_42.setFont(font)
        self.PD_42.setObjectName(_fromUtf8("PD_42"))
        self.gridLayout_7.addWidget(self.PD_42, 0, 1, 1, 1)
        self.PD_38 = QtGui.QCheckBox(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.PD_38.setFont(font)
        self.PD_38.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.PD_38.setObjectName(_fromUtf8("PD_38"))
        self.gridLayout_7.addWidget(self.PD_38, 0, 0, 1, 1)
        self.PR = QtGui.QCheckBox(self.page_3)
        self.PR.setGeometry(QtCore.QRect(10, 70, 171, 17))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.PR.setFont(font)
        self.PR.setObjectName(_fromUtf8("PR"))
        self.PN = QtGui.QCheckBox(self.page_3)
        self.PN.setGeometry(QtCore.QRect(10, 100, 171, 17))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.PN.setFont(font)
        self.PN.setObjectName(_fromUtf8("PN"))
        self.DH_AnnII = QtGui.QCheckBox(self.page_3)
        self.DH_AnnII.setGeometry(QtCore.QRect(10, 130, 201, 17))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.DH_AnnII.setFont(font)
        self.DH_AnnII.setObjectName(_fromUtf8("DH_AnnII"))
        self.protections.addItem(self.page_3, _fromUtf8(""))
        self.Emprise.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayoutWidget_12 = QtGui.QWidget(self.tab_4)
        self.gridLayoutWidget_12.setGeometry(QtCore.QRect(30, 30, 481, 130))
        self.gridLayoutWidget_12.setObjectName(_fromUtf8("gridLayoutWidget_12"))
        self.gridLayout_10 = QtGui.QGridLayout(self.gridLayoutWidget_12)
        self.gridLayout_10.setMargin(0)
        self.gridLayout_10.setVerticalSpacing(20)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_10.addWidget(self.label_7, 0, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.gridLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_10.addWidget(self.label_14, 2, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.gridLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_10.addWidget(self.label_12, 1, 1, 1, 1)
        self.buffer = QtGui.QLineEdit(self.gridLayoutWidget_12)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buffer.sizePolicy().hasHeightForWidth())
        self.buffer.setSizePolicy(sizePolicy)
        self.buffer.setMaximumSize(QtCore.QSize(100, 16777215))
        self.buffer.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.buffer.setAlignment(QtCore.Qt.AlignCenter)
        self.buffer.setObjectName(_fromUtf8("buffer"))
        self.gridLayout_10.addWidget(self.buffer, 2, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget_12)
        self.label_8.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_10.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget_12)
        self.label_9.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_10.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget_12)
        self.label_10.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_10.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.tab_4)
        self.label_15.setGeometry(QtCore.QRect(70, 180, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_11 = QtGui.QLabel(self.tab_4)
        self.label_11.setGeometry(QtCore.QRect(40, 180, 12, 16))
        self.label_11.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.bouton_geom = QtGui.QCheckBox(self.tab_4)
        self.bouton_geom.setGeometry(QtCore.QRect(190, 180, 21, 16))
        self.bouton_geom.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.bouton_geom.setFont(font)
        self.bouton_geom.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bouton_geom.setText(_fromUtf8(""))
        self.bouton_geom.setIconSize(QtCore.QSize(20, 20))
        self.bouton_geom.setObjectName(_fromUtf8("bouton_geom"))
        self.Emprise.addTab(self.tab_4, _fromUtf8(""))

        self.retranslateUi(SICEN)
        self.Emprise.setCurrentIndex(0)
        self.protections.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), SICEN.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), SICEN.reject)
        QtCore.QMetaObject.connectSlotsByName(SICEN)

    def retranslateUi(self, SICEN):
        SICEN.setWindowTitle(QtGui.QApplication.translate("SICEN", "SICEN", None, QtGui.QApplication.UnicodeUTF8))
        self.Titre.setText(QtGui.QApplication.translate("SICEN", "Ouverture des observations SICEN", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("SICEN", "Observateur(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("SICEN", "Localisation", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("SICEN", "Commune n°1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("SICEN", "Commune n°2", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("SICEN", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("SICEN", "Supérieur à :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("SICEN", "Inférieur à :", None, QtGui.QApplication.UnicodeUTF8))
        self.Emprise.setTabText(self.Emprise.indexOf(self.tab_2), QtGui.QApplication.translate("SICEN", "Généralités", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("SICEN", "Règne", None, QtGui.QApplication.UnicodeUTF8))
        self.Animalia.setText(QtGui.QApplication.translate("SICEN", "Animal", None, QtGui.QApplication.UnicodeUTF8))
        self.Plantae.setText(QtGui.QApplication.translate("SICEN", "Végétal", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("SICEN", "Nom Complet : ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("SICEN", "Nom Vernaculaire : ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("SICEN", "Ordre :", None, QtGui.QApplication.UnicodeUTF8))
        self.Emprise.setTabText(self.Emprise.indexOf(self.tab), QtGui.QApplication.translate("SICEN", "Filtre par Taxons", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("SICEN", "Départementales", None, QtGui.QApplication.UnicodeUTF8))
        self.LRD_38.setText(QtGui.QApplication.translate("SICEN", "Isère - 38", None, QtGui.QApplication.UnicodeUTF8))
        self.LRD_01.setText(QtGui.QApplication.translate("SICEN", "Ain - 01", None, QtGui.QApplication.UnicodeUTF8))
        self.LRD_07.setText(QtGui.QApplication.translate("SICEN", "Ardèche - 07", None, QtGui.QApplication.UnicodeUTF8))
        self.LRD_26.setText(QtGui.QApplication.translate("SICEN", "Drôme - 26", None, QtGui.QApplication.UnicodeUTF8))
        self.LRD_42.setText(QtGui.QApplication.translate("SICEN", "42 - Loire", None, QtGui.QApplication.UnicodeUTF8))
        self.LRD_69.setText(QtGui.QApplication.translate("SICEN", "69 - Rhône", None, QtGui.QApplication.UnicodeUTF8))
        self.LRD_73.setText(QtGui.QApplication.translate("SICEN", "73 - Savoie", None, QtGui.QApplication.UnicodeUTF8))
        self.LRD_74.setText(QtGui.QApplication.translate("SICEN", "74 - Haute-Savoie", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("SICEN", "Régionales", None, QtGui.QApplication.UnicodeUTF8))
        self.LRR_Flore.setText(QtGui.QApplication.translate("SICEN", "Flore", None, QtGui.QApplication.UnicodeUTF8))
        self.LRR_Oiseaux.setText(QtGui.QApplication.translate("SICEN", "Oiseaux", None, QtGui.QApplication.UnicodeUTF8))
        self.LRR_Autre.setText(QtGui.QApplication.translate("SICEN", "Autre", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("SICEN", "Nationales", None, QtGui.QApplication.UnicodeUTF8))
        self.LRN_Autre.setText(QtGui.QApplication.translate("SICEN", "Autre", None, QtGui.QApplication.UnicodeUTF8))
        self.LRN_Flore.setText(QtGui.QApplication.translate("SICEN", "Flore", None, QtGui.QApplication.UnicodeUTF8))
        self.LRN_Oiseaux.setText(QtGui.QApplication.translate("SICEN", "Oiseaux", None, QtGui.QApplication.UnicodeUTF8))
        self.LRN_Ortho.setText(QtGui.QApplication.translate("SICEN", "Orthoptères", None, QtGui.QApplication.UnicodeUTF8))
        self.UICN.setText(QtGui.QApplication.translate("SICEN", "UICN", None, QtGui.QApplication.UnicodeUTF8))
        self.LRE.setText(QtGui.QApplication.translate("SICEN", "Liste Rouge Européenne", None, QtGui.QApplication.UnicodeUTF8))
        self.protections.setItemText(self.protections.indexOf(self.page_2), QtGui.QApplication.translate("SICEN", "Listes Rouges", None, QtGui.QApplication.UnicodeUTF8))
        self.PATRIMONIALITE.setText(QtGui.QApplication.translate("SICEN", "Espèces Patrimoniales en Rhône-Alpes", None, QtGui.QApplication.UnicodeUTF8))
        self.PATRI38.setText(QtGui.QApplication.translate("SICEN", "Isère - 38", None, QtGui.QApplication.UnicodeUTF8))
        self.PATRI01.setText(QtGui.QApplication.translate("SICEN", "Ain - 01", None, QtGui.QApplication.UnicodeUTF8))
        self.PATRI07.setText(QtGui.QApplication.translate("SICEN", "Ardèche - 07", None, QtGui.QApplication.UnicodeUTF8))
        self.PATRI26.setText(QtGui.QApplication.translate("SICEN", "Drôme - 26", None, QtGui.QApplication.UnicodeUTF8))
        self.PATRI42.setText(QtGui.QApplication.translate("SICEN", "42 - Loire", None, QtGui.QApplication.UnicodeUTF8))
        self.PATRI69.setText(QtGui.QApplication.translate("SICEN", "69 - Rhône", None, QtGui.QApplication.UnicodeUTF8))
        self.PATRI73.setText(QtGui.QApplication.translate("SICEN", "73 - Savoie", None, QtGui.QApplication.UnicodeUTF8))
        self.PATRI74.setText(QtGui.QApplication.translate("SICEN", "74 - Haute-Savoie", None, QtGui.QApplication.UnicodeUTF8))
        self.ZNIEFF.setText(QtGui.QApplication.translate("SICEN", "Espèces Déterminantes ZNIEFF", None, QtGui.QApplication.UnicodeUTF8))
        self.protections.setItemText(self.protections.indexOf(self.page), QtGui.QApplication.translate("SICEN", "Patrimonialités", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("SICEN", "Départementales", None, QtGui.QApplication.UnicodeUTF8))
        self.PD_42.setText(QtGui.QApplication.translate("SICEN", "42 - Loire", None, QtGui.QApplication.UnicodeUTF8))
        self.PD_38.setText(QtGui.QApplication.translate("SICEN", "Isère - 38", None, QtGui.QApplication.UnicodeUTF8))
        self.PR.setText(QtGui.QApplication.translate("SICEN", "Régionale", None, QtGui.QApplication.UnicodeUTF8))
        self.PN.setText(QtGui.QApplication.translate("SICEN", "Nationale", None, QtGui.QApplication.UnicodeUTF8))
        self.DH_AnnII.setText(QtGui.QApplication.translate("SICEN", "Directive Habitat - Annexe II", None, QtGui.QApplication.UnicodeUTF8))
        self.protections.setItemText(self.protections.indexOf(self.page_3), QtGui.QApplication.translate("SICEN", "Protections", None, QtGui.QApplication.UnicodeUTF8))
        self.Emprise.setTabText(self.Emprise.indexOf(self.tab_3), QtGui.QApplication.translate("SICEN", "Filtre par Patrimonialités / Protections", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("SICEN", "Sélectionnez une table", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("SICEN", "Déterminez un tampon autour du polygone (en mètre)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("SICEN", "Sélectionnez un polygone dans cette table", None, QtGui.QApplication.UnicodeUTF8))
        self.buffer.setText(QtGui.QApplication.translate("SICEN", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("SICEN", "1.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("SICEN", "2.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("SICEN", "3.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("SICEN", "Cochez cette case", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("SICEN", "4.", None, QtGui.QApplication.UnicodeUTF8))
        self.Emprise.setTabText(self.Emprise.indexOf(self.tab_4), QtGui.QApplication.translate("SICEN", "Filtre par Emprise", None, QtGui.QApplication.UnicodeUTF8))

